version: 2.1

jobs:
  update:
    docker:
      - image: cimg/node:latest
    steps:
      - checkout
      - run: "git config --global user.email aeneasr@users.noreply.github.com"
      - run: "git config --global user.name aeneasr"
      - run: ./update.sh

workflows:
  welcome:
    jobs:
      - update:
          name: Update Dependents
          filters:
            branches:
              only: master
