version: 2.1

jobs:
  update:
    docker:
      - image: circleci/node:14.3.0
    working_directory: ~/docusaurus-template
    steps:
      - checkout
      - run: >
          mkdir -p ~/.config/gh &&
          echo '{
            "hosts": {
              "github.com": {
                "oauth_token": "'"$GITHUB_API_TOKEN"'",
                "user": "zepatrik"
              }
            }
          }' > ~/.config/gh/config.yml
      - run: "git config --global user.email aeneasr@users.noreply.github.com"
      - run: "git config --global user.name aeneasr"
      - run: ./update.sh

workflows:
  update:
    jobs:
      - update:
          name: Update Dependents
          filters:
            branches:
              only: master
