name: Check format

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run format:check
